project_id = "uewuiiopkctdtaexmtxu"

[functions.ai-chat]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.zoho-callback]
verify_jwt = false

[functions.send-customer-otp]
verify_jwt = false

[functions.verify-customer-otp]
verify_jwt = false

[functions.create-geidea-session]
verify_jwt = false

[functions.geidea-webhook]
verify_jwt = false

[functions.send-platform-otp]
verify_jwt = false

[functions.verify-platform-otp]
verify_jwt = false

[functions.process-geidea-callback]
verify_jwt = false
